"""initial migrations

Revision ID: a4065ab0c573
Revises: 
Create Date: 2024-09-05 00:40:44.347083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4065ab0c573'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Actuator',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('fanStatus', sa.Boolean(), nullable=True),
    sa.Column('flapperStatus', sa.Boolean(), nullable=True),
    sa.Column('heaterStatus', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('Sensor',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('soilMoistureContent', sa.DOUBLE_PRECISION(), nullable=True),
    sa.Column('waterFlow', sa.DOUBLE_PRECISION(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sensor')
    op.drop_table('Actuator')
    # ### end Alembic commands ###
